### ISSUE TITLE
Meta: MVP to do list.

### ISSUE THREAD

**Issue by matthewhammer** [dfinity/motoko.rs#2]
@rvanasa and @matthewhammer are working in tandem towards an MVP of this library/tool.

This issue tracks the "main to do list" of this MVP.

- [x] adapt cases from parser.mly in moc source into corresponding cases in parser.lalrpop here
- [x] write basic pretty printer, in format module (to help us see and test the parsed ASTs in a manageable way). The formatter need not do actual formatting. No context-sensitive whitespace choices needed. It's just to see the parsed ASTs for very small programs.
- [x] test parses for basic expressions, trying to cover the "core" language syntax, excluding class and actor definitions initially.
- **optional:** test formatter and parser together: that each example program "round-trips" in the parser-formatter-parser combined flow.

**Comment by matthewhammer** [comment]
Closing this issue.

We've since crossed this threshold, for a subset of Motoko that we could call "core Motoko without function, actor or type definitions".

The remaining cases of the syntax are not challenging to parse, but before supporting those cases we are first focused on an interpreter for this smaller subset.  See #12.

We are also focused on formatting issues.  See #11
